#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"
cd ..


# This is a local build as of now, but it can be easily migrated to download
# the classpath from GitHub
bootstrap_knob() {
    mkdir custom-scripting/.knob 2>/dev/null
    rm -rf custom-scripting/.knob/runtime
    mkdir custom-scripting/.knob/runtime/ 2>/dev/null
    ./gradlew knob-scripting:installDist -q --console=plain
    cp -f -R knob-scripting/build/install/knob-scripting/lib/ custom-scripting/.knob/runtime/
}

bootstrap_knob

cd custom-scripting
classpath=$(ls -1 .knob/runtime | sed 's/^/.knob\/runtime\//' | tr '\n' :)
kotlinc -classpath "$classpath" -script knob.kts -- "$@"
